### ISSUE TITLE
Percent-encoded padding support

### ISSUE THREAD

**Issue by stevenroose** [kalaspuffar/base64url#2]
[RFC 4648 states](https://tools.ietf.org/html/rfc4648#section-5):
```
The pad character "=" is typically percent-encoded when used in an
   URI [9], but if the data length is known implicitly, this can be
   avoided by skipping the padding; see section 3.2.
```

Currently, a percent encoded padding character, `%3D`, is not explicitely recognized (not as far as I can read the code). Does the implementation assume that prior URL decoding has already happened?

Over at Crypto-Conditions ([issue](https://github.com/interledgerjs/five-bells-condition/issues/62)), they interpreted the spec as prohibiting padding characters.

**Comment by kalaspuffar** [comment]
Hi Steven.

I don't have any strong opinions on if the library should have the functionality to decode the padding character.

We could add a simple remove part to remove any trailing ```%3d```. I still think the library should handle the count to insure the block size is correct so any extra padding should be removed before decode.

Adding this functionality will make the library more robust but then again if you call the go routine normally this will be decoded before it enters the code so it should not be an issue. 

Could become an issue if you handle saved links perhaps, but the general case doesn't require this to be added. 

Thoughts?

best regards
Daniel

**Comment by stevenroose** [comment]
Yeah upon second consideration, the percent encoding should be done separately I think, not in the scope of this lib.
