### ISSUE TITLE
Decode should throw an error when an illegal base64url character is encountered

### ISSUE THREAD

**Issue by stevenroose** [kalaspuffar/base64url#3]
The supermethod `base64.StdEncoding.DecodeString` also throws when a non-base64 character is encountered, so `base64url.Decode` should also throw when an illegal base64url character is encountered.

**Comment by stevenroose** [comment]
It could be easily added using a regex.. I can do that if you want..

**Comment by stevenroose** [comment]
See #4. I opted for a more efficient check than a regexp.

**Comment by kalaspuffar** [comment]
Thanks for your great contribution.
